/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.unisinu.tallerpro.guias.jdpo.ventanas;

import co.edu.unisinu.tallerpro.guias.jdpo.Principal;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author JoseP
 */
public class EjercicioABPLogin extends javax.swing.JFrame {

    /**
     * Creates new form EjercicioABPLogin
     */
    public EjercicioABPLogin() {
        initComponents();
        Color col=new Color(255,255,255);
        getContentPane().setBackground(col);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        etiUsuario = new javax.swing.JLabel();
        etiPassword = new javax.swing.JLabel();
        LoginUsuario = new javax.swing.JTextField();
        LoginPassword = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ABP Asignaturas");
        setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jButton1.setText("INICIAR SECCION");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jButton2.setText("REGISTRARSE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel1.setText("BIENVENIDO POR FAVOR ELIJA UNA OPCION");

        etiUsuario.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        etiUsuario.setText("USUARIO");

        etiPassword.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        etiPassword.setText("PASSWORD");

        LoginUsuario.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        LoginUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginUsuarioActionPerformed(evt);
            }
        });

        LoginPassword.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(etiPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(etiUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(44, 44, 44)
                            .addComponent(LoginUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1))
                .addGap(76, 76, 76))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LoginUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String usuario;
        String password;
        usuario = LoginUsuario.getText();
        password = LoginPassword.getText();
        if (Principal.usuarios.stream().filter(user -> user.id.equals(usuario)
                && user.password.equals(password)).findAny().isPresent()) {
            ventanaABP miVentana = new ventanaABP();
            miVentana.setLocationRelativeTo(null);
            miVentana.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Usuario no existente o incorrecto");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String usuario;
        String password;
        String password2 = JOptionPane.showInputDialog(null,"Por favor ingrese nuevamente su password.");
        password2 = password2.trim();
        boolean tienemayusculas = false;
        boolean tienenumero = false;
        boolean tienecaracterespecial = false;
        boolean tienelongitud = false;
        usuario = LoginUsuario.getText();
        password = LoginPassword.getText();
        boolean passnoempty = password.isEmpty();
        boolean passnoempty2 = password2.isEmpty();
        boolean passiguales = password.equals(password2);

        
        
        password = password.trim();
        if(passnoempty){
            JOptionPane.showMessageDialog(null, "Los campos no pueden estar vacios. ");
        }
        if (!passiguales) {
            JOptionPane.showMessageDialog(null, "Las password no son iguales");
        }
            for (int i = 0; i < password2.length(); i++) {
                char caracter = password2.charAt(i);
                int longitud = password2.length();
                if (Character.isUpperCase(caracter)) {
                    tienemayusculas = true;
                }
                if (Character.isDigit(caracter)) {
                    tienenumero = true;
                }
                if (Character.isLetterOrDigit(caracter) == false) {
                    tienecaracterespecial = true;
                }
                if (longitud >= 8) {
                    tienelongitud = true;
                }
            }
            if (tienemayusculas == false) {
                JOptionPane.showMessageDialog(null, "Debe tener al menos una mayuscula");
            }
            if (tienenumero == false) {
                JOptionPane.showMessageDialog(null, "Debe tener al menos un numero");
            }
            if (tienecaracterespecial == false) {
                JOptionPane.showMessageDialog(null, "Debe tener al menos un caracter especial");
            }
            if (tienelongitud == false) {
                JOptionPane.showMessageDialog(null, "Debe tener al menos 8 caracteres");
            }
            if(tienemayusculas && tienenumero  && tienecaracterespecial  && tienelongitud  && !passnoempty && !passnoempty2 && passiguales){
            JOptionPane.showMessageDialog(null, "Registro EXITOSO ahora ya puede iniciar seccion.");
            Usuario user = new Usuario();
            user.id = usuario;
            user.password = password;
            Principal.usuarios.add(user);

        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void LoginUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EjercicioABPLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EjercicioABPLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EjercicioABPLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EjercicioABPLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EjercicioABPLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField LoginPassword;
    private javax.swing.JTextField LoginUsuario;
    private javax.swing.JLabel etiPassword;
    private javax.swing.JLabel etiUsuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
